In [21]:
!pip install clean-text


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 53 kB 1.2 MB/s 
     |████████████████████████████████| 175 kB 10.1 MB/s 
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171046 sha256=455593ff2bf43b23b9443c0ac7479dd89e229f76f96ea38b079fade80c8bfe18
  Stored in directory: /root/.cache/pip/wheels/8a/4e/b6/57b01db010d17ef6ea9b40300af725ef3e210cb1acfb7ac8b6
Successfully built emoji


In [27]:
import os
import re
import tensorflow as tf;
import numpy as npp
from tensorflow.keras.layers import TextVectorization
import pandas as pd
from cleantext import clean
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords




In [9]:
modelToxicityDetector = tf.keras.models.load_model('./toxicityDetector.h5')

In [12]:
CSV_PATH = os.path.join('sample_data','test.csv') # providing the path to the import csv wrt the notebook

In [14]:
data = pd.read_csv(CSV_PATH,encoding='utf-8') #importing csv using pandas

In [15]:
data.duplicated().sum() #duplicated entries

0

In [16]:
data.drop_duplicates(keep='first',inplace=True)

In [26]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [28]:
#removing numbers puncuations
data['cleaned'] = data['comment_text'].apply(lambda x:re.sub('[^A-Za-z]',' ' ,x))
#lowercasing
data['lower'] = data['cleaned'].apply(lambda x:x.lower())
#removing punctuations
data['rem_punkt'] = data['lower'].apply(lambda x: clean(x, no_punct=True))
#tokenizing
data['tokenized'] = data['rem_punkt'].apply(lambda x: word_tokenize(x))
#removing stop words
data['final'] = data['tokenized'].apply(lambda t: [x for x in t if x not in stopwords .words ('english')])


In [29]:
data["final_data"] = data["final"].apply(lambda x: " ".join(x))
data

id                                       comment_text  \
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...   
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...   
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...   
3       00017563c3f7919a  :If you have a look back at the source, the in...   
4       00017695ad8997eb          I don't anonymously edit articles at all.   
...                  ...                                                ...   
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...   
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...   
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...   
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...   
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...   

                                                  cleaned  \
0       Yo bitch Ja Rule is more succesful then you ll...   
1          From RfC       The title is fine as it is  ...   
2               Sources         Zawe Ashton on Lapland...   
3        If you have a look back at the source  the in...   
4               I don t anonymously edit articles at all    
...                                                   ...   
153159      i totally agree  this stuff is nothing but...   
153160     Throw from out field to home plate        D...   
153161          Okinotorishima categories       I see ...   
153162            One of the founding nations of the E...   
153163         Stop already  Your bullshit is not welc...   

                                                    lower  \
0       yo bitch ja rule is more succesful then you ll...   
1          from rfc       the title is fine as it is  ...   
2               sources         zawe ashton on lapland...   
3        if you have a look back at the source  the in...   
4               i don t anonymously edit articles at all    
...                                                   ...   
153159      i totally agree  this stuff is nothing but...   
153160     throw from out field to home plate        d...   
153161          okinotorishima categories       i see ...   
153162            one of the founding nations of the e...   
153163         stop already  your bullshit is not welc...   

                                                rem_punkt  \
0       yo bitch ja rule is more succesful then you ll...   
1                 from rfc the title is fine as it is imo   
2                          sources zawe ashton on lapland   
3       if you have a look back at the source the info...   
4                i don t anonymously edit articles at all   
...                                                   ...   
153159  i totally agree this stuff is nothing but too ...   
153160  throw from out field to home plate does it get...   
153161  okinotorishima categories i see your changes a...   
153162  one of the founding nations of the eu germany ...   
153163  stop already your bullshit is not welcome here...   

                                                tokenized  \
0       [yo, bitch, ja, rule, is, more, succesful, the...   
1       [from, rfc, the, title, is, fine, as, it, is, ...   
2                    [sources, zawe, ashton, on, lapland]   
3       [if, you, have, a, look, back, at, the, source...   
4       [i, don, t, anonymously, edit, articles, at, all]   
...                                                   ...   
153159  [i, totally, agree, this, stuff, is, nothing, ...   
153160  [throw, from, out, field, to, home, plate, doe...   
153161  [okinotorishima, categories, i, see, your, cha...   
153162  [one, of, the, founding, nations, of, the, eu,...   
153163  [stop, already, your, bullshit, is, not, welco...   

                                                    final  \
0       [yo, bitch, ja, rule, succesful, ever, whats, ...   
1                  

In [30]:
MAX_WORDS = 200000 #no of words in the vocabulory
vectorizer = TextVectorization(max_tokens=MAX_WORDS,
                               output_sequence_length=1800,
                               output_mode='int');


In [64]:
X = data['final_data']
y = pd.read_csv('sample_data/test_labels.csv',encoding='utf-8')
y.replace(-1,1)
vectorizer.adapt(X.values)
X.values

array(['yo bitch ja rule succesful ever whats hating sad mofuckas bitch slap ur pethedic white faces get kiss ass guys sicken ja rule pride da music man dont diss shit nothin wrong bein like tupac brother fuckin white boys get things right next time',
       'rfc title fine imo', 'sources zawe ashton lapland', ...,
       'okinotorishima categories see changes agree correct gotten confused found acknowledging japan territorial rights okinotorishima however category acknowledge japan claim exclusive economic zone eez stemming okinotorishima category disputed eez',
       'one founding nations eu germany law return quite similar israel actually true germany allows people whose ancestors citizens germany return afaik allow descendants anglo saxons return angeln saxony israel contrast allows jews return israel even trace particular ancestral line anyone lived modern state even mandate palestine',
       'stop already bullshit welcome fool think kind explination enough well pity'],
      dt

In [65]:
y = y[y.columns[1:]].values


In [66]:
y

array([[-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       ...,
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [57]:
vectorizer.adapt(X.values)

In [58]:
vectorized_text = vectorizer(X.values) #passing the numpy array to the vectorizer and vectorizing all text

In [59]:
vectorized_text # 159571 - no of entries in the dataset , #1800 - output seq length wich is the max num of words a sentence might have. 0 s are given if it does to have that many words

<tf.Tensor: shape=(153164, 1800), dtype=int64, numpy=
array([[ 1344,   125,  2934, ...,     0,     0,     0],
       [  906,   215,   510, ...,     0,     0,     0],
       [   28, 87596,  6571, ...,     0,     0,     0],
       ...,
       [52615,   991,    11, ...,     0,     0,     0],
       [    8,  5373,  2133, ...,     0,     0,     0],
       [   86,   141,   599, ...,     0,     0,     0]])>

In [67]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))

In [70]:
dataset = dataset.cache()
dataset = dataset.shuffle(160000) #160000 - buffersize
dataset = dataset.batch(16) #each batch has 16 samples
dataset = dataset.prefetch(8) # helps bottlenecks
testDataset = dataset.take(int(len(dataset)*1)) 


In [71]:
test_batch_X , test_batch_y = testDataset.as_numpy_iterator().next()

In [ ]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy


In [ ]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()


In [ ]:
for batch in testDataset.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch;
    # Make a prediction 
    yhat = model.predict(X_true);
    
    # Flatten the predictions
    y_true = y_true.flatten();
    yhat = yhat.flatten();
    
    pre.update_state(y_true, yhat);
    re.update_state(y_true, yhat);
    acc.update_state(y_true, yhat);


In [ ]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')